mylibber_backend_hello:
    pattern:  /hello/{name}
    defaults: { _controller: MylibberBackendBundle:Default:hello }
mylibber_backend_homepage:
    pattern:  /admin/
    defaults: { _controller: MylibberBackendBundle:Default:index }

mylibber_backend_addbook:
    pattern:  /admin/addbook
    defaults: { _controller: MylibberBackendBundle:Book:add  }

mylibber_backend_addnew:
    pattern:  /admin/addnew
    defaults: { _controller: MylibberBackendBundle:Book:addnew  }
mylibber_backend_deletebook:
    pattern:    /admin/deltebook/{id}
    defaults:  { _controller: MylibberBackendBundle:Book:deletebook }



mylibber_backend_histbook:
    pattern:  /admin/histbook
    defaults: { _controller: MylibberBackendBundle:Book:hist  }

mylibber_backend_usermanage:
    pattern:  /admin/usermanage
    defaults: { _controller: MylibberBackendBundle:Book:usermanage  }

mylibber_backend_config:
    pattern:  /admin/config
    defaults: { _controller: MylibberBackendBundle:Book:config  }


mylibber_backend_addCategory:
    pattern:   /admin/addCategory
    defaults:  { _controller: MylibberBackendBundle:Category:addCategory }

mylibber_backend_addCategoryNew:
    pattern:   /admin/addCategoryNew
    defaults:  { _controller: MylibberBackendBundle:Category:addCategoryNew }

mylibber_backend_deleteCategory:
    pattern:   /admin/deleteCategory/{id}
    defaults:  { _controller: MylibberBackendBundle:Category:deleteCategory }


mylibber_backend_addUser:
    pattern:   /admin/addUser
    defaults:  { _controller: MylibberBackendBundle:User:addUser }
mylibber_backend_addUserNew:
    pattern:   /admin/addUserNew
    defaults:  { _controller: MylibberBackendBundle:User:addUserNew }
mylibber_backend_deleteUser:
    pattern:   /admin/deleteUser/{id}
    defaults:  { _controller: MylibberBackendBundle:User:deleteUser }
mylibber_backend_updateUserForm:
    pattern:   /admin/updateUserForm/{id}
    defaults:  { _controller: MylibberBackendBundle:User:updateUserForm }
mylibber_backend_updateUser:
    pattern:   /admin/updateUser/{id}
    defaults:  { _controller: MylibberBackendBundle:User:updateUser}


mylibber_backend_borrbook:
    pattern:  /admin/borrbook
    defaults: { _controller: MylibberBackendBundle:Borr:borr  }

mylibber_backend_borrform:
    pattern:   /admin/borrForm/{id}
    defaults:  { _controller: MylibberBackendBundle:Borr:borrForm }

mylibber_backend_newBorrBook:
    pattern:   /admin/newBorrBook/{id}
    defaults: { _controller: MylibberBackendBundle:Borr:newBorrBook }

mylibber_backend_borrList:
    pattern:  /admin/borrList
    defaults:  { _controller: MylibberBackendBundle:Borr:borrList }
mylibber_backend_borrSearchList:
    pattern:  /admin/borrSearchList
    defaults:  { _controller: MylibberBackendBundle:Borr:borrSearchList}
mylibber_backend_isbnBorrList:
    pattern:  /admin/isbnBorrList/{bookIsbn}
    defaults: { _controller: MylibberBackendBundle:Borr:isbnBorrList }

mylibber_backend_giveBack:
    pattern: /admin/giveBack/{bookIsbn}
    defaults: {_controller: MylibberBackendBundle:Book:giveBack}

#ebook
mylibber_backend_addebookform:
    pattern:    /admin/addebookform
    defaults:   { _controller: MylibberBackendBundle:Ebook:addebookform }
mylibber_backend_addebook:
    pattern:    /admin/addebook
    defaults:   { _controller: MylibberBackendBundle:Ebook:addebook }

mylibber_backend_showebook:
    pattern:    /admin/showebook
    defaults: {_controller: MylibberBackendBundle:Ebook:showebook}